# Project 1: Binominal Trees


## Intro: 
This notebook will cover the following analysis:
* Binominal Trees European Options Pricing
* Black-Scholes model for pricing
* Least Squares Line (Trees vs Black-Scholes)
* Convergence Rate of Binaominal Treesfor increasing steps 

## Part A: Binominal Trees

In [31]:
import math
import numpy as np
import matplotlib.pyplot as plt

In [32]:
# Data
k = 10
r = 0.02
sig = 0.25
t = 0.25
s = 10
u = math.exp(sig*math.sqrt(t))
d = 1 / u
p = (math.exp(r * t) - d) / (u - d)
N = [10, 100, 1000, 10000]

### In order to obtain a feasible runtime, use dynamic programming approach (O(n^2) vs. O(2^n))

In [33]:
# Build table
def tableBuild(n):
    # Height = n, Width = n + 1
    return np.zeros([n, n+1], dtype=int)

In [37]:
def binominal_trees(i, j, N, s):
    # Base Case:
    if (i == N - 1):
        # Set table
        node = s * u - k
        tree[i][j] = node
        visual()
        return s * u - k
    # Recurse
    elif (tree[i+1][j] == 0 and tree[i+1][j-1] == 0): 
        # compute both left and right nodes
        s_up = s * u
        s_down = s * d
        node = math.exp(-1 * r * t) * (p * binominal_trees(i+1, j, N, s_up) + (1 - p) * binominal_trees(i+1, j-1, N, s_down))
        tree[i][j] = node
        visual()
        return node
    else:
        # compute only left node
        s_down = s * d
        node = math.exp(-1 * r * t) * (tree[i+1][j] + (1 - p) * binominal_trees(i+1, j-1, N, s_down))
        tree[i][j] = node
        visual()
        return node
    

In [38]:
def visual():
    print(tree)

## Part B: Bloack-Scholes 

In [ ]:
def black_scholes():

## Part C: Results Table

In [ ]:
# Return |E| for all N
def differences():


In [40]:
# main compute loop for parts A - C
# Get C for N = 10, 100, 1,000, 10,000
# for i in range(len(N)):

n = 3
tree = tableBuild(n)
C = binominal_trees(0, n, n, 10)
print(C)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 4]]
[[0 0 0 0]
 [0 0 0 2]
 [0 0 1 4]]
[[ 0  0  0  0]
 [ 0  0  0  2]
 [ 0 -1  1  4]]
[[ 0  0  0  0]
 [ 0  0  0  2]
 [ 0 -1  1  4]]
[[ 0  0  0  1]
 [ 0  0  0  2]
 [ 0 -1  1  4]]
1.6077176503653903


## Part D: Plot of Least Squares

## Part E: Convergence Rate of Binominal Trees
write soln here